### ISSUE TITLE
本地static文件夹的子文件夹中无文件

### ISSUE THREAD

**Issue by tufu9441** [gyk001/hexo-qiniu-sync#19]
您好，我按照说明安装了插件，并在_config.yml配置文件中添加了如下的插件设置：
```
qiniu:
  offline: false
  sync: true
  bucket: haomwei
  access_key: 我的ak
  secret_key: 我的sk
  dirPrefix: static
  urlPrefix: http://haomwei.qiniudn.com/static
  local_dir: static
  update_exist: true
  image: 
    folder: images
    extend: 
  js:
    folder: js
  css:
    folder: css
```
但是在运行hexo clean和hexo generate之后，发现static文件夹中的images，js和css子文件夹内没有任何文件，这样我运行hexo qiniu sync也就没有向我的七牛空间中上传任何文件，请问是我使用的姿势不对还是哪里出了问题呢？非常感谢！
