### ISSUE TITLE
code: 400, error: incorrect zone, please use up-z1.qiniu.com

### ISSUE THREAD

**Issue by Jaybeka** [gyk001/hexo-qiniu-sync#33]
`_config.yml`配置如下：

```
qiniu:
  offline: false
  sync: true
  bucket: github-pages
  secret_file: /Users/yangsicong/Documents/qn.json
  access_key: AccessKey
  secret_key: SecretKey
  dirPrefix: 
  urlPrefix: http://up-z1.qiniu.com/
  local_dir: static
  update_exist: true
  image:
    folder: images
    extend:
  js:
    folder: js
  css:
    folder: css
```

最初`urlPrefix`配置按照文档说明配置是`http://github-pages.qiniudn.com/static`，但命令行报错：

```
{ code: 400,
  error: 'incorrect zone, please use up-z1.qiniu.com' }
```

我把urlPrefix改成`http://up-z1.qiniu.com/`还是`https://up-z1.qiniu.com/`都还是报同样的问题。

这是为什么呢？
