### ISSUE TITLE
hexo-qiniu-sync安装好后，hexo s命令不见了，hexo d也提示问题

### ISSUE THREAD

**Issue by nextInnovationUcas** [gyk001/hexo-qiniu-sync#41]
hexo-qiniu-sync安装好后，hexo s命令不见了，hexo d也提示问题ERROR Deployer not found: git，如果把config.yml里面的插件配置描述去掉，hexo s又可以用了，d也没问题。

**Comment by Simmer-Jun** [comment]
同样遇到这个问题，只要在config.yml里面写上插件配置在命令行的`hexo server`就失效。。。

**Comment by gyk001** [comment]
config.yml里的plugins段不配置hexo-qiniu-sync也可以正常使用吧？

**Comment by Simmer-Jun** [comment]
@nextInnovationUcas  @gyk001  把config.yml 中的plugins去掉但是 qiniu字段及配置字段保留，可以正常开启本地服务并且插件开启正常！  Thx~ @gyk001

**Comment by nextInnovationUcas** [comment]
谢谢，回头试试～～我当时弄了半天没弄好，就直接在浏览器装了个qiniu插件。

以上。

发自我的 iPhone

**Comment by Exlany** [comment]
同样遇到这个问题

**Comment by Exlany** [comment]
plugins段注释掉，解决了问题，没注意看回复（捂脸，逃

**Comment by xirong** [comment]
plugins 注释掉就 OK 了，同样解决问题。👍

**Comment by nextInnovationUcas** [comment]
但我就是想使用这个插件啊……注掉咋用。

发自我的 iPhone

**Comment by MeetDevin** [comment]
我的天，这bug！ 天坑！幸好我看到了这里

**Comment by andycall** [comment]
把文档更新了吧。。文档上的配置已经错了

**Comment by thjiang** [comment]
还好看到了这里+1

被这个问题折腾了好久了

**Comment by sc610889477** [comment]
弱弱问下我报了这个错误
```
FATAL duplicated mapping key at line 101, column 3:
      folder: js
      ^
YAMLException: duplicated mapping key at line 101, column 3:
      folder: js
```
我觉得我没写错啊
 ```
up_host: http://upload.qiniu.com
  local_dir: static
  update_exist: true
  image:
        folder: images
  #extend:
  js:
        folder: js
  css:
        folder: css

```
