### ISSUE TITLE
Hexo目录下,如何把自身的一些背景图,js,css用七牛加载呢

### ISSUE THREAD

**Issue by imbajin** [gyk001/hexo-qiniu-sync#43]
a. 首先说一下题外话:插件很好,但是我觉得有些必要的说明太少了,网上的资料也太少.所以有时候可能只是一个很低级的配置问题,半天找不到解决办法,十分蛋疼.
加上有一些参数自身跟作者理解有区别,就更难发现,
贴下我目前的配置.

```
qiniu:
  offline: false
  sync: true
  bucket: imbax
  # secret_file: sec/qn.json  #这个参数不知道如何配置,为空会报错,先注释了只能
  access_key: 7ytnNGqnStBSgPdP4QEzwVYW7wE80XXXXXXXX
  secret_key: fgrF7XBmoIuPTybJIvk3LVIyCWHA7OUXXXXXXXX
  dirPrefix: 
  urlPrefix: http://xxxxx.bkt.clouddn.com/
  up_host: http://upload.qiniu.com
  local_dir: **public**
  update_exist: true
  image: 
    folder: img
    extend: 
  js:
    folder: js
  css:
    folder: css
  # background:  #添加的其他文件夹没有生效,可能不支持这样写
  #    folder: 
```

>   1.然后这样七牛就会自动把hexo根目录下的public文件夹都上传进去,但是这样还是无法调用,实际网站还是用的本身的服务器.问下如何能让特别是那种背景图片(动辄上百k压缩后)放到七牛加速呢.
> 再就是写文章的时候如果经常要插图,难道只能先把图丢在本地的比如 public/img 目录下,然后先同步,再复制一个个图片的外链到文章么,那太蛋疼了一点吧.
>    2.之前有一次离线使用hexo,发现这个插件在离线的时候会报一堆错误,那时候文章并没有调用七牛,local_dir也写的是public,然后也是跟之前的同学一样的 ERROR: xxx/xxx.png无法找到之类的.也不知道为什么,配置跟上面一样.然后我hexo clean 之后才勉强能部署,但是时间一长又会报错,只能把七牛文件全删掉重新上传.  希望能解决. 再就是发现默认的模板 plugin: xxxxhexo-qiniu  那个设置很容易出错.
> 而且很难发现,如果可以去掉,希望更新一下说明,我在几台机器上都是一样,删掉那个-不换行, 或者直接不要那个说明都可以运行,但是加了就无限报错.

也是初用hexo跟七牛不久,希望能指点一下.   或者邮箱给个联系方式可行?不甚感谢
