### ISSUE TITLE
FATAL duplicated mapping key at xxxx  folder: js

### ISSUE THREAD

**Issue by sc610889477** [gyk001/hexo-qiniu-sync#59]
不知道为什么，直接从github教程上复制下来的，总是报错
```
qiniu:
  offline: false
  sync: true
  bucket: ***//这个我就不透露了
  secret_file: ./qiniu_key.json
  access_key: *******************
  secret_key: *********************
  dirPrefix: tomato
  urlPrefix: http://****.qiniudn.com/tomato
  up_host: http://upload.qiniu.com
  local_dir: public
  update_exist: true
  image:
        folder: images
  extend:
  js:
        folder: js
  css:
        folder: css
```
